### ISSUE TITLE
[Bug] Copy is broken

### ISSUE THREAD

**Issue by magedhelmy1** [ztjhz/BetterChatGPT#314]
When trying to copy text, the following error happens:

```
CodeBlock.tsx:44 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')
    at onClick (CodeBlock.tsx:44:35)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12
```

**Comment by ztjhz** [comment]
Is the website served with http? In http, cannot copy items.

**Comment by ztjhz** [comment]
We do plan to add these in the future.
