### ISSUE TITLE
Blank white screen when loading the page.

### ISSUE THREAD

**Issue by CrispTails** [ztjhz/BetterChatGPT#424]
I get a blank white screen whenever I try to load onto BetterChatGPT.

**Comment by albeorla** [comment]
Experience the same thing.

```
Uncaught SyntaxError: Invalid or unexpected token (at index-1e99a67a.js:11:98944)
```

**Comment by victoralvelais** [comment]
> Experiencing the same thing.
> 
> ```
> Uncaught SyntaxError: Invalid or unexpected token (at index-1e99a67a.js:11:98944)
> ```

I'm also experiencing this error

**Comment by greengeckowizard** [comment]
having the same issue

**Comment by albeorla** [comment]
I checked out the UI locally and did not have any issues.

**Comment by ztjhz** [comment]
What browsers are all of you using?

**Comment by albeorla** [comment]
Chrome for me both for live (not working) and and locally (working).

**Comment by greengeckowizard** [comment]
Chrome

**Comment by CrispTails** [comment]
Opera.

**Comment by victoralvelais** [comment]
I get this on my desktop Edge, but not locally. I also got it on iOS safari but I haven't experienced it since I cleared cookies. Clearing cookies doesn't seem to work on desktop though.

**Comment by almaziphone** [comment]
Safari Chrome IOS 14.2. White screen

**Comment by ckt1031** [comment]
Where did you host it?
I got this error once I turn on Cloudflare proxy, the error is gone once it turned it off.

**Comment by CrispTails** [comment]
> Where did you host it? I got this error once I turned on Cloudflare proxy, the error was gone once it turned it off.

I'm just using [bettergpt.chat](url). Not hosting a fork.

**Comment by victoralvelais** [comment]
Any fix for this? Still experiencing on mobile.

**Comment by victoralvelais** [comment]
Looks like I can force it to load properly if I delete the cache and reload from a new IP.
