### ISSUE TITLE
Sometimes GPT will answer in a super weird way. I guess some prompts are missing.

### ISSUE THREAD

**Issue by pea3nut** [ztjhz/BetterChatGPT#464]
You can import the dialogue by importing the JSON content below then click the submit button.
I tried the same prompts in the OpenAI playground. The GPT can answer it correctly to give me the code, but the BetterGPT web app will output some unuseful sentences. It looks like some prompts are missing

```json
[{"id":"dd092d64-fbe0-4e8b-addb-a314925a0126","title":"Copy of Copy of Copy of 在线英语字典项目设计概述","messages":[{"content":"你是一个资深的全栈工程师，负责开发一个项目，它是一个在线的英语字典，用户提交他要查询的词，然后返回内容\n\n## 项目信息\n\n技术栈：\n\n- Next.js v10\n- Antd v4\n- React v16\n- Typescript v4\n- Node.js v14\n- MySQL v5.7\n\n整个程序设计如下：\n\n- 程序分为 3 个主要部分：\n  - 页面（pages）：一个前端页面，通常拥有自己的 URL。\n  - CGI 接口：一个后端 HTTP 或 WebSocket 接口\n  - 小鸟模块（bridie-module）：一个 JS 文件，通常也是一个 Class\n- 依赖关系如下：\n  - “页面”调用“CGI接口”来拿取数据\n  - “CGI接口”调用“小鸟模块”来实现功能\n  - “小鸟模块”调用一些底层能力（如 MySQL、Node AIP）来完成功能的封装\n- 页面包含：首页、单词详情页\n- CGI 接口包含：\n  - /chat/history/:diolog_id：根据 dilog_id 获取 dialog 的相关信息\n  - /chat/add-on：给某个对话追加一条消息\n  - /chat/about-word/:word_id：根据一个词，来创建一个对话\n  - /word/info/:id：获取词信息\n  - /word/submit：提交一个词进行查询\n  - /search：搜索词，返回可能的候选词\n  - /feed/word：获取推荐阅读的词列表，目前只有最新创建的词，20个\n  - /feed/chat：获取某个词下面推荐阅读的对话列表，当用户对话完成后，关闭是点击“有帮助”会被记录为一次有效的对话，然后可以从这个接口取到。目前也只有最新创建的对话，20个\n  - /feed/push/chat：当用户对话完成后，关闭是点击“有帮助”，dialog_id 会被记录\n- 小鸟模块包含：\n  - WordDb： 关于单词存储相关的功能实现\n  - WordStore：关于单词相关的功能的高层实现，依赖于 WordDb\n  - DialogueDb： 关于对话存储相关的功能实现\n  - DialogueStore：关于对话相关的功能的高层实现，依赖于 DialogueDb\n  - FeedDb： 关于推荐阅读（推荐单词、推荐对话来不）存储相关的功能实现\n  - FeedStore：关于推荐阅读（推荐单词、推荐对话来不）相关的功能的高层实现，依赖于 FeedDb\n  - PromptGenerator：用来生成发送给 GPT 的 Prompts，以及将 GPT 的返回解析成格式化的数据\n\n## 指示\n\n当我让你写代码时，你应当：\n\n1. 输出完整的代码，而不是伪代码\n2. 代码中有丰富的注释\n\n当我问你调研类的技术问题，你应该：\n\n1. 围绕着这个项目来给出2-5个不同维度的意见。比如我问你要存贮一个词的数据时，你应该给出文件存储、某个具体数据库比如SQL、NoSQL存储等多个方案，\n2. 通过多个维度来对比利弊\n\n当我发你代码和报错是，你应该：\n\n1. 分析报错原因，给出修改意见\n2. 输出修改后的完整的、全量的代码，而不是只给出 diff 或者修改的地方。你应该给出全量的代码，对于不需要修改的地方，重述即可","role":"system"},{"content":"下面是 WordDb 的模块文档：\n\n<markdown>\n# WordDb 模块文档\n\n## 模块概述\n\nWordDb模块是一个依赖于MySQL和内存存储的模块，主要负责对单词的增删改查操作。该模块包含7个方法，其中2个方法依赖于内存数据，其余5个方法依赖于MySQL。\n\n## 接口定义\n\n```typescript\ninterface WordDb {\n  /**\n   * 从内存中移除正在生成状态中的词\n   * @param wordId 单词ID\n   * @returns Promise<void>\n   */\n  deleteProcessingWord(wordId: string): Promise<void>;\n\n  /**\n   * 将一个正在生成的词存储到内存中\n   * @param wordId 单词ID\n   * @param readableStream 可读流\n   * @returns Promise<void>\n   */\n  createProcessingWord(wordId: string, readableStream: ReadableStream): Promise<void>;\n\n  /**\n   * 从MySQL中获取单词的全量数据\n   * @param wordId 单词ID\n   * @returns Promise<Word> 返回一个Promise，resolve的结果是一个Word对象\n   */\n  getWordById(wordId: string): Promise<Word>;\n\n  /**\n   * 在MySQL中创建一个新的单词记录\n   * @param word Word对象\n   * @returns Promise<string> 返回一个Promise，resolve的结果是新创建的单词ID\n   */\n  createWord(word: Word): Promise<string>;\n\n  /**\n   * 在MySQL中删除一个单词记录\n   * @param wordId 单词ID\n   * @returns Promise<void>\n   */\n  deleteWord(wordId: string): Promise<void>;\n\n  /**\n   * 在MySQL中更新一个单词记录\n   * @param wordId 单词ID\n   * @param word Word对象\n   * @returns Promise<void>\n   */\n  updateWord(wordId: string, word: Word): Promise<void>;\n\n  /**\n   * 在模块初始化时，删除MySQL中所有状态为processing的单词记录\n   * @returns Promise<void>\n   */\n  deleteProcessingWordsOnInitialization(): Promise<void>;\n\n  /**\n   * 根据原始词查询单词的全量数据\n   * @param originalWord 原始词\n   * @returns Promise<Word | null> 返回一个Promise，resolve的结果是一个Word对象或null\n   */\n  getByOriginalWord(originalWord: string): Promise<Word | null>;\n}\n\ninterface Word {\n  id: string;\n  status: WordStatus; // WordStatus是一个枚举类型，表示单词的状态\n  promptVersion: string;\n  createTime: Date;\n  wordDoc?: string; // wordDoc是一个可选属性，表示单词的详细信息，可能在单词创建时为空，后续通过updateWord方法更新\n}\n\nenum WordStatus {\n  PROCESSING = 'processing',\n  COMPLETED = 'completed'\n}\n```\n\n## 方法详解\n\n### deleteProcessingWord\n\n该方法用于从内存中移除正在生成状态中的词。传入一个单词ID，该方法会从内存中的processingWordMap中删除对应的记录。\n\n### createProcessingWord\n\n该方法用于将一个正在生成的词存储到内存中。传入一个单词ID和一个可读流，该方法会将这两个参数存储到内存中的processingWordMap中。同时，该方法会监听传入的可读流，当可读流结束时，会自动调用deleteProcessingWord方法，从内存中删除对应的记录。\n\n### getWordById\n\n该方法用于从MySQL中获取单词的全量数据。传入一个单词ID，该方法会在MySQL中查询对应的记录，并返回一个包含单词全量数据的Promise。\n\n### createWord\n\n该方法用于在MySQL中创建一个新的单词记录。传入一个Word对象，该方法会在MySQL中插入一条新的记录，并返回一个包含新创建的单词ID的Promise。\n\n### deleteWord\n\n该方法用于在MySQL中删除一个单词记录。传入一个单词ID，该方法会在MySQL中删除对应的记录。\n\n### updateWord\n\n该方法用于在MySQL中更新一个单词记录。传入一个单词ID和一个Word对象，该方法会在MySQL中找到对应的记录，并使用传入的Word对象更新该记录。\n\n### deleteProcessingWordsOnInitialization\n\n该方法在模块初始化时调用，用于删除MySQL中所有状态为processing的单词记录。因为processing状态的单词相关的信息存储在内存中，如果服务崩溃，这些信息会丢失，所以需要在服务启动时清理MySQL中的这些记录。\n\n### getByOriginalWord\n\n该方法用于根据原始词查询单词的全量数据。传入一个原始词，该方法会在MySQL中查询对应的记录，如果查到了，返回一个包含单词全量数据的Promise，如果查不到，返回null。\n</markdown>","role":"system"},{"role":"user","content":"\n word-db.ts 代码如下：\n\n```ts\nimport {v4 as uuidv4} from 'uuid';\nimport * as mysql from 'mysql2/promise';\nimport {Readable} from 'stream';\n\n/**\n * WordDb 类用于处理与单词相关的数据库操作。\n *\n * @class WordDb\n */\nclass WordDb {\n    private connection: mysql.Connection;\n    private processingWordMap: Map<string, Readable>;\n\n    /**\n     * 创建一个新的 WordDb 实例。\n     *\n     * @param {mysql.Connection} connection - MySQL 连接对象。\n     */\n    constructor(connection: mysql.Connection) {\n        this.connection = connection;\n        this.processingWordMap = new Map();\n    }\n\n    /**\n     * 将一个正在生成的词存储到内存中。\n     *\n     * @param {string} wordId - 单词ID。\n     * @param {Readable} readableStream - 可读流。\n     * @returns {Promise<void>}\n     */\n    async createProcessingWord(wordId: string, readableStream: Readable): Promise<void> {\n        // 将单词ID和对应的可读流存储到内存中\n        this.processingWordMap.set(wordId, readableStream);\n        // 当可读流结束时，从内存中移除对应的单词ID\n        readableStream.on('end', () => {\n            this.processingWordMap.delete(wordId);\n        });\n    }\n\n    /**\n     * 从内存中移除正在生成状态中的词。\n     *\n     * @param {string} wordId - 单词ID。\n     * @returns {Promise<void>}\n     */\n    async deleteProcessingWord(wordId: string): Promise<void> {\n        // 从内存中移除对应的单词ID\n        this.processingWordMap.delete(wordId);\n    }\n\n    /**\n     * 在初始化时删除所有正在生成状态中的词。\n     *\n     * @returns {Promise<void>}\n     */\n    async deleteProcessingWordsOnInitialization(): Promise<void> {\n        // 清理内存中的数据\n        this.processingWordMap.clear();\n\n        // 清理MySQL中的数据\n        await this.connection.execute(\n            `DELETE FROM words WHERE status = 'processing'`\n        );\n    }\n\n    /**\n     * 创建一个新的单词记录。\n     *\n     * @param {string} originalWord - 原始单词。\n     * @param {string} status - 单词状态。\n     * @param {string} promptVersion - 提示版本。\n     * @param {string} createTime - 创建时间。\n     * @param {string} wordDoc - 单词文档。\n     * @returns {Promise<string>} 返回新创建的单词ID。\n     */\n    async createWord(originalWord: string, status: string, promptVersion: string, createTime: string, wordDoc: string): Promise<string> {\n        // 生成一个新的UUID作为单词ID\n        const id = uuidv4();\n\n        // 在数据库中创建一个新的单词记录\n        const [rows] = await this.connection.execute(\n            `INSERT INTO words (id, original_word, status, prompt_version, create_time, word_doc) VALUES (?, ?, ?, ?, ?, ?)`,\n            [id, originalWord, status, promptVersion, createTime, wordDoc]\n        );\n\n        // 如果创建成功，返回新创建的单词ID\n        if (rows.affectedRows > 0) {\n            return id;\n        } else {\n            throw new Error('Failed to create word');\n        }\n    }\n\n    /**\n     * 根据单词ID获取单词信息。\n     *\n     * @param {string} wordId - 单词ID。\n     * @returns {Promise<any>} 返回单词信息。\n     */\n    async getWordById(wordId: string): Promise<any> {\n        // 在数据库中查询对应的单词记录\n        const [rows] = await this.connection.execute(\n            `SELECT * FROM words WHERE id = ?`,\n            [wordId]\n        );\n\n        // 如果查询成功，返回单词信息\n        if (rows.length > 0) {\n            const word = rows[0];\n            return {\n                id: word.id,\n                originalWord: word.original_word,\n                status: word.status,\n                promptVersion: word.prompt_version,\n                createTime: word.create_time,\n                wordDoc: word.word_doc\n            };\n        } else {\n            throw new Error(`Word with id ${wordId} not found`);\n        }\n    }\n\n    /**\n     * 根据单词ID删除单词记录。\n     *\n     * @param {string} wordId - 单词ID。\n     * @returns {Promise<void>}\n     */\n    async deleteWord(wordId: string): Promise<void> {\n        // 在数据库中删除对应的单词记录\n        const [rows] = await this.connection.execute(\n            `DELETE FROM words WHERE id = ?`,\n            [wordId]\n        );\n\n        // 如果删除失败，抛出异常\n        if (rows.affectedRows === 0) {\n            throw new Error(`Word with id ${wordId} not found`);\n        }\n    }\n\n    /**\n     * 更新单词记录。\n     *\n     * @param {string} id - 单词ID。\n     * @param {string} originalWord - 原始单词。\n     * @param {string} status - 单词状态。\n     * @param {string} promptVersion - 提示版本。\n     * @param {string} createTime - 创建时间。\n     * @param {string} wordDoc - 单词文档。\n     * @returns {Promise<void>}\n     */\n    async updateWord(id: string, originalWord: string, status: string, promptVersion: string, createTime: string, wordDoc: string): Promise<void> {\n        // 在数据库中更新对应的单词记录\n        const [rows] = await this.connection.execute(\n            `UPDATE words SET original_word = ?, status = ?, prompt_version = ?, create_time = ?, word_doc = ? WHERE id = ?`,\n            [originalWord, status, promptVersion, createTime, wordDoc, id]\n        );\n\n        // 如果更新失败，抛出异常\n        if (rows.affectedRows === 0) {\n            throw new Error(`Word with id ${id} not found`);\n        }\n    }\n\n    /**\n     * 根据原始单词获取单词信息。\n     *\n     * @param {string} originalWord - 原始单词。\n     * @returns {Promise<any>} 返回单词信息。\n     */\n    async getByOriginalWord(originalWord: string): Promise<any> {\n        // 在数据库中查询对应的单词记录\n        const [rows] = await this.connection.execute(\n            `SELECT * FROM words WHERE original_word = ?`,\n            [originalWord]\n        );\n\n        // 如果查询成功，返回单词信息\n        if (rows.length > 0) {\n            const word = rows[0];\n            return {\n                id: word.id,\n                originalWord: word.original_word,\n                status: word.status,\n                promptVersion: word.prompt_version,\n                createTime: word.create_time,\n                wordDoc: word.word_doc\n            };\n        } else {\n            throw new Error(`Word with original word ${originalWord} not found`);\n        }\n    }\n}\n\n// 使用示例\n(async () => {\n    const connection = await mysql.createConnection({\n        host: 'localhost',\n        port: 8081,\n        user: 'root',\n        password: 'root',\n        database: 'ai_dictionary',\n    });\n\n    const wordDb = new WordDb(connection);\n\n    // 创建一个可读流\n    const readableStream = new Readable();\n    readableStream.push('Hello, world!');\n    readableStream.push(null);\n\n    // 将可读流存储到内存中\n    await wordDb.createProcessingWord('1', readableStream);\n\n    // 从内存中删除可读流\n    await wordDb.deleteProcessingWord('1');\n\n    // 在初始化时删除所有正在生成状态中的词\n    await wordDb.deleteProcessingWordsOnInitialization();\n\n    const wordId = await wordDb.createWord('example', 'active', '1.0', new Date().toISOString(), 'Example word document');\n\n    console.log(`Created word with id ${wordId}`);\n\n    const word = await wordDb.getWordById(wordId);\n    console.log(`Retrieved word: ${JSON.stringify(word)}`);\n\n    await wordDb.updateWord(wordId, 'example', 'inactive', '1.0', new Date().toISOString(), 'Example word document');\n    console.log(`Updated word with id ${wordId}`);\n\n    const wordByOriginal = await wordDb.getByOriginalWord('example');\n    console.log(`Retrieved word by original: ${JSON.stringify(wordByOriginal)}`);\n\n    await wordDb.deleteWord(wordId);\n    console.log(`Deleted word with id ${wordId}`);\n})();\n```\n\n\n报错，请修复错误：\n\n```bash\n$ ./node_modules/.bin/ts-node modules/word-db.ts\n/home/pea3nut/_pea3nut/aidict/web-app/node_modules/ts-node/src/index.ts:859\n    return new TSError(diagnosticText, diagnosticCodes, diagnostics);\n           ^\nTSError: ⨯ Unable to compile TypeScript:\nmodules/word-db.ts:87:18 - error TS2339: Property 'affectedRows' does not exist on type 'OkPacket | RowDataPacket[] | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | ProcedureCallPacket'.\n  Property 'affectedRows' does not exist on type 'RowDataPacket[]'.\n\n87         if (rows.affectedRows > 0) {\n                    ~~~~~~~~~~~~\nmodules/word-db.ts:108:18 - error TS2339: Property 'length' does not exist on type 'OkPacket | RowDataPacket[] | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | ProcedureCallPacket'.\n  Property 'length' does not exist on type 'OkPacket'.\n\n108         if (rows.length > 0) {\n                     ~~~~~~\nmodules/word-db.ts:137:18 - error TS2339: Property 'affectedRows' does not exist on type 'OkPacket | RowDataPacket[] | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | ProcedureCallPacket'.\n  Property 'affectedRows' does not exist on type 'RowDataPacket[]'.\n\n137         if (rows.affectedRows === 0) {\n                     ~~~~~~~~~~~~\nmodules/word-db.ts:161:18 - error TS2339: Property 'affectedRows' does not exist on type 'OkPacket | RowDataPacket[] | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | ProcedureCallPacket'.\n  Property 'affectedRows' does not exist on type 'RowDataPacket[]'.\n\n161         if (rows.affectedRows === 0) {\n                     ~~~~~~~~~~~~\nmodules/word-db.ts:180:18 - error TS2339: Property 'length' does not exist on type 'OkPacket | RowDataPacket[] | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | ProcedureCallPacket'.\n  Property 'length' does not exist on type 'OkPacket'.\n\n180         if (rows.length > 0) {\n                     ~~~~~~\n\n    at createTSError (/home/pea3nut/_pea3nut/aidict/web-app/node_modules/ts-node/src/index.ts:859:12)\n    at reportTSError (/home/pea3nut/_pea3nut/aidict/web-app/node_modules/ts-node/src/index.ts:863:19)\n    at getOutput (/home/pea3nut/_pea3nut/aidict/web-app/node_modules/ts-node/src/index.ts:1077:36)\n    at Object.compile (/home/pea3nut/_pea3nut/aidict/web-app/node_modules/ts-node/src/index.ts:1433:41)\n    at Module.m._compile (/home/pea3nut/_pea3nut/aidict/web-app/node_modules/ts-node/src/index.ts:1617:30)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Object.require.extensions.<computed> [as .ts] (/home/pea3nut/_pea3nut/aidict/web-app/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {\n  diagnosticCodes: [ 2339, 2339, 2339, 2339, 2339 ]\n}\n```"}],"config":{"max_tokens":2093,"model":"gpt-4","temperature":1,"presence_penalty":0,"top_p":1,"frequency_penalty":0},"titleSet":true}]
```

**Comment by jeske** [comment]
this addon has nothing to do with how GPT responds to your prompts.. it is just a user interface over OpenAI's GPT

**Comment by pea3nut** [comment]
@jeske GPT is able to answer it correctly. I have tried on the playground of OpneIA. But when I call GPT via this addon, it cannot.
